name: przywory
type: drupal9
docroot: web
php_version: "8.0"
webserver_type: apache-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
project_tld: loc
additional_hostnames:
  - "*.przywory"
additional_fqdns: []
mariadb_version: "10.3"
mysql_version: ""
provider: default
use_dns_when_possible: true
composer_version: "2"
